FROM golang:alpine as builder


WORKDIR /go/src/github.com/llr104/slgserver
COPY . .

RUN apk --no-cache add tzdata \
    && go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -o httpserver ./main/httpserver.go

FROM alpine as final


WORKDIR /go/src/github.com/llr104/slgserver

COPY --from=builder /go/src/github.com/llr104/slgserver/httpserver ./
COPY --from=builder /go/src/github.com/llr104/slgserver/data ./data/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
ENV TZ=Asia/Shanghai

EXPOSE 8088
ENTRYPOINT ./httpserver
