FROM golang:alpine as builder


WORKDIR /go/src/github.com/llr104/slgserver
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -o httpserver ./main/httpserver.go

FROM golang:alpine


WORKDIR /go/src/github.com/llr104/slgserver

COPY --from=0 /go/src/github.com/llr104/slgserver/httpserver ./
COPY --from=0 /go/src/github.com/llr104/slgserver/data ./data/

EXPOSE 8088
ENTRYPOINT ./httpserver
