FROM golang:alpine as builder


WORKDIR /go/src/github.com/llr104/slgserver
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -o gateserver ./main/gateserver.go

FROM alpine as final



WORKDIR /go/src/github.com/llr104/slgserver

COPY --from=builder /go/src/github.com/llr104/slgserver/gateserver ./
COPY --from=builder /go/src/github.com/llr104/slgserver/data ./data/

EXPOSE 8004
ENTRYPOINT ./gateserver
